if(EXISTS "/home/student/Desktop/HWSE-Hospital/HWSE-Hospital_test_tests-b12d07c.cmake")
  include("/home/student/Desktop/HWSE-Hospital/HWSE-Hospital_test_tests-b12d07c.cmake")
else()
  add_test(HWSE-Hospital_test_NOT_BUILT-b12d07c HWSE-Hospital_test_NOT_BUILT-b12d07c)
endif()
